# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sunspot_plus"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Louis Gillies"]
  s.date = "2013-01-04"
  s.description = "A library of extensions for outoftime's sunspot gem for solr indexing server. Using the session adapter design pattern to add support for:\n    1) delayed_job to move indexing commits out of process.\n    Support for case insensitive sort fields by creating indexed copy of fields transformed for sort.\n  "
  s.email = "louisgillies@yahoo.co.uk"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/sunspot_plus.rb",
    "lib/sunspot_plus/dsl/fields.rb",
    "lib/sunspot_plus/dsl/query/case_insensitive_sort.rb",
    "lib/sunspot_plus/session_proxy/delayed_job/indexing_job.rb",
    "lib/sunspot_plus/session_proxy/delayed_job/safe_configuration.rb",
    "lib/sunspot_plus/session_proxy/delayed_job_session_proxy.rb",
    "lib/sunspot_plus/session_proxy/silent_fail_session_proxy.rb",
    "lib/sunspot_plus/type/case_insensitive_sort_type.rb"
  ]
  s.homepage = "http://github.com/playgood/sunspot_plus"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Extensions for outoftime's sunspot gem."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

