require 'sunspot'
require 'sunspot_plus/session_proxy/delayed_job_session_proxy'
require 'sunspot_plus/session_proxy/silent_fail_session_proxy'
require 'sunspot_plus/session_proxy/delayed_job/indexing_job'
require 'sunspot_plus/session_proxy/delayed_job/safe_configuration'